// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using budget_server.Data;

#nullable disable

namespace budget_server.Migrations
{
    [DbContext(typeof(BudgetContext))]
    partial class BudgetContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("budget_server.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("budget_server.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Archived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsIncome")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("budget_server.Models.MonthlyBudget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Year", "Month")
                        .IsUnique();

                    b.ToTable("MonthlyBudgets");
                });

            modelBuilder.Entity("budget_server.Models.ProjectedExpense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonthlyBudgetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("MonthlyBudgetId");

                    b.ToTable("ProjectedExpenses");
                });

            modelBuilder.Entity("budget_server.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("BankTransactionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Date")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonthlyBudgetId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProjectedExpenseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("MonthlyBudgetId");

                    b.HasIndex("ProjectedExpenseId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("budget_server.Models.ProjectedExpense", b =>
                {
                    b.HasOne("budget_server.Models.Category", "Category")
                        .WithMany("ProjectedExpenses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("budget_server.Models.MonthlyBudget", "MonthlyBudget")
                        .WithMany("ProjectedExpenses")
                        .HasForeignKey("MonthlyBudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("MonthlyBudget");
                });

            modelBuilder.Entity("budget_server.Models.Transaction", b =>
                {
                    b.HasOne("budget_server.Models.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("budget_server.Models.MonthlyBudget", "MonthlyBudget")
                        .WithMany("Transactions")
                        .HasForeignKey("MonthlyBudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("budget_server.Models.ProjectedExpense", "ProjectedExpense")
                        .WithMany("Transactions")
                        .HasForeignKey("ProjectedExpenseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");

                    b.Navigation("MonthlyBudget");

                    b.Navigation("ProjectedExpense");
                });

            modelBuilder.Entity("budget_server.Models.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("budget_server.Models.Category", b =>
                {
                    b.Navigation("ProjectedExpenses");
                });

            modelBuilder.Entity("budget_server.Models.MonthlyBudget", b =>
                {
                    b.Navigation("ProjectedExpenses");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("budget_server.Models.ProjectedExpense", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
